exclude: ["CNAME", ".gitignore", "Gemfile", "Gemfile.lock", "LICENSE"]

# Page categories (for making navbar)
all_cats: ['index', 'research', 'cv']
cat_titles: ['Home', 'Research', 'CV']

markdown: kramdown
